//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libreriaMiniMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public int id_categoria { get; set; }
        public int id_proveedor { get; set; }
        public int id_marca { get; set; }
        public int id_medida { get; set; }
        public double cantidad { get; set; }
        public double precio_unitario { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual marca marca { get; set; }
        public virtual medida medida { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
