//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.MiniMarket.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tproducto
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public string medidas { get; set; }
        public int cantidad { get; set; }
        public decimal precio { get; set; }
        public int marcaid { get; set; }
        public int proveedorid { get; set; }
        public int categoriaid { get; set; }
    
        public virtual tcategoria tcategoria { get; set; }
        public virtual tmarca tmarca { get; set; }
        public virtual tproveedor tproveedor { get; set; }
    }
}
